-- Phase 7B Payment Gateway

ALTER TABLE `audit_logs` MODIFY COLUMN `action` ENUM(
  'REGISTER', 'LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'LOGOUT_ALL',
  'PASSWORD_RESET_REQUEST', 'PASSWORD_RESET', 'PASSWORD_CHANGED', 'EMAIL_CHANGED',
  'EMAIL_VERIFIED', 'EMAIL_VERIFICATION_SENT', 'ACCOUNT_LOCKED', 'USER_LOCKED',
  'USER_UNLOCKED', 'SESSION_REVOKED', 'USER_SUSPENDED', 'USER_BANNED',
  'ROLE_CHANGED', 'ACCOUNT_DELETED',
  'PROFILE_UPDATED', 'COMPANY_CREATED', 'COMPANY_UPDATED', 'COMPANY_DELETED',
  'MEMBER_INVITED', 'MEMBER_ACCEPTED', 'MEMBER_REMOVED', 'OWNERSHIP_TRANSFERRED',
  'EMPLOYER_VERIFICATION_UPDATED', 'COMPANY_VERIFICATION_UPDATED', 'COMPANY_STATUS_CHANGED',
  'PROVINCE_UPDATED', 'CITY_UPDATED',
  'CATEGORY_CREATED', 'CATEGORY_UPDATED', 'CATEGORY_DELETED',
  'SUBCATEGORY_CREATED', 'SUBCATEGORY_UPDATED', 'SUBCATEGORY_DELETED',
  'SKILL_CREATED', 'SKILL_UPDATED', 'SKILL_DELETED',
  'TECHNOLOGY_CREATED', 'TECHNOLOGY_UPDATED', 'TECHNOLOGY_DELETED',
  'TAXONOMY_SUGGESTION_CREATED', 'TAXONOMY_SUGGESTION_APPROVED',
  'TAXONOMY_SUGGESTION_REJECTED', 'TAXONOMY_SUGGESTION_MERGED',
  'JOB_CREATED', 'JOB_UPDATED', 'JOB_PUBLISHED', 'JOB_PAUSED', 'JOB_CLOSED', 'JOB_DELETED',
  'JOB_APPROVED',
  'APPLICATION_SUBMITTED', 'APPLICATION_WITHDRAWN', 'APPLICATION_STATUS_CHANGED', 'APPLICATION_VIEWED',
  'RESUME_CREATED', 'RESUME_UPDATED', 'RESUME_VISIBILITY_CHANGED', 'RESUME_STATUS_CHANGED',
  'RESUME_EDUCATION_CREATED', 'RESUME_EDUCATION_UPDATED', 'RESUME_EDUCATION_DELETED',
  'RESUME_EXPERIENCE_CREATED', 'RESUME_EXPERIENCE_UPDATED', 'RESUME_EXPERIENCE_DELETED',
  'RESUME_SKILL_UPDATED', 'RESUME_TECHNOLOGY_UPDATED',
  'RESUME_LANGUAGE_CREATED', 'RESUME_LANGUAGE_UPDATED', 'RESUME_LANGUAGE_DELETED',
  'RESUME_CERTIFICATE_CREATED', 'RESUME_CERTIFICATE_UPDATED', 'RESUME_CERTIFICATE_DELETED',
  'RESUME_PROJECT_CREATED', 'RESUME_PROJECT_UPDATED', 'RESUME_PROJECT_DELETED',
  'PLAN_CREATED', 'PLAN_UPDATED', 'PLAN_FEATURE_VERSIONED', 'PLAN_PRICE_UPDATED',
  'SUBSCRIPTION_CREATED', 'SUBSCRIPTION_CHANGED', 'SUBSCRIPTION_CANCELED', 'SUBSCRIPTION_HISTORY_RECORDED',
  'WALLET_CREDITED', 'WALLET_DEBITED',
  'AI_CREDIT_RESERVED', 'AI_CREDIT_CAPTURED', 'AI_CREDIT_RELEASED',
  'QUOTA_CONSUMED', 'CONTACT_UNLOCKED', 'SYSTEM_SETTING_UPDATED', 'BILLING_ADMIN_GRANT',
  'PAYMENT_CREATED', 'PAYMENT_SUCCEEDED', 'PAYMENT_FAILED', 'PAYMENT_SETTLED', 'PAYMENT_REFUNDED', 'PAYMENT_CANCELLED'
) NOT NULL;

CREATE TABLE `payments` (
  `id` VARCHAR(191) NOT NULL,
  `owner_type` ENUM('USER', 'COMPANY') NOT NULL,
  `owner_id` VARCHAR(36) NOT NULL,
  `sku` VARCHAR(80) NOT NULL,
  `amount` INTEGER NOT NULL,
  `currency` VARCHAR(3) NOT NULL,
  `status` ENUM('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'REFUNDED') NOT NULL DEFAULT 'PENDING',
  `gateway` VARCHAR(40) NOT NULL,
  `gateway_ref` VARCHAR(120) NULL,
  `idempotency_key` VARCHAR(120) NOT NULL,
  `refund_amount` INTEGER NULL,
  `refunded_at` DATETIME(3) NULL,
  `metadata` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `payments_idempotency_key_key`(`idempotency_key`),
  INDEX `payments_owner_type_owner_id_idx`(`owner_type`, `owner_id`),
  INDEX `payments_gateway_ref_idx`(`gateway_ref`),
  INDEX `payments_status_idx`(`status`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `payment_attempts` (
  `id` VARCHAR(191) NOT NULL,
  `payment_id` VARCHAR(191) NOT NULL,
  `status` VARCHAR(40) NOT NULL,
  `raw_request` JSON NULL,
  `raw_response` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `payment_attempts_payment_id_created_at_idx`(`payment_id`, `created_at`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `payment_attempts` ADD CONSTRAINT `payment_attempts_payment_id_fkey` FOREIGN KEY (`payment_id`) REFERENCES `payments`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
